import type { DependencyGraph } from "./graph-types"

const ROOT =
  "market:ethereum-1:0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48:ausdc"

export const SAMPLE_GRAPH: DependencyGraph = {
  root: ROOT,
  nodes: [
    { id: ROOT, type: "market", label: "aUSDC" },
    { id: "protocol:ethereum-1:aave-v3", type: "protocol", label: "Aave V3" },
    { id: "primitive-token:ethereum-1:usdc", type: "primitive_token", label: "USDC" },
    { id: "primitive-token:ethereum-1:aave", type: "primitive_token", label: "AAVE" },
    { id: "wrapper:ethereum-1:btc-b", type: "wrapper", label: "BTC.b" },
    { id: "primitive-token:ethereum-1:btc", type: "primitive_token", label: "BTC" },
    { id: "protocol:ethereum-1:avalanche-bridge", type: "protocol", label: "Avalanche Bridge" },
    { id: "wrapper:ethereum-1:cbbtc", type: "wrapper", label: "cbBTC" },
    { id: "protocol:ethereum-1:coinbase", type: "protocol", label: "Coinbase" },
    { id: "wrapper:ethereum-1:cbeth", type: "wrapper", label: "cbETH" },
    { id: "primitive-token:ethereum-1:eth", type: "primitive_token", label: "ETH" },
    { id: "wrapper:ethereum-1:ebtc", type: "wrapper", label: "eBTC" },
    { id: "protocol:ethereum-1:ether-fi", type: "protocol", label: "Ether.fi" },
    { id: "wrapper:ethereum-1:fbtc", type: "wrapper", label: "FBTC" },
    { id: "protocol:ethereum-1:frax", type: "protocol", label: "Frax" },
    { id: "wrapper:ethereum-1:lbtc", type: "wrapper", label: "LBTC" },
    { id: "protocol:ethereum-1:lombard", type: "protocol", label: "Lombard" },
    { id: "position:ethereum-1:pt-susde-5feb2026", type: "position", label: "PT-sUSDE-5FEB2026" },
    { id: "wrapper:ethereum-1:susde", type: "wrapper", label: "sUSDE" },
    { id: "primitive-token:ethereum-1:usde", type: "primitive_token", label: "USDe" },
    { id: "protocol:ethereum-1:ethena", type: "protocol", label: "Ethena" },
    { id: "protocol:ethereum-1:pendle", type: "protocol", label: "Pendle" },
    { id: "position:ethereum-1:pt-usde-5feb2026", type: "position", label: "PT-USDe-5FEB2026" },
    { id: "primitive-token:ethereum-1:pyusd", type: "primitive_token", label: "PYUSD" },
    { id: "wrapper:ethereum-1:reth", type: "wrapper", label: "rETH" },
    { id: "protocol:ethereum-1:rocket-pool", type: "protocol", label: "Rocket Pool" },
    { id: "market:ethereum-1:syrupusdt", type: "market", label: "syrupUSDT" },
    { id: "primitive-token:ethereum-1:usdt", type: "primitive_token", label: "USDT" },
    { id: "protocol:ethereum-1:maple", type: "protocol", label: "Maple" },
    { id: "wrapper:ethereum-1:tbtc", type: "wrapper", label: "tBTC" },
    { id: "protocol:ethereum-1:threshold-network", type: "protocol", label: "Threshold Network" },
    { id: "wrapper:ethereum-1:wbtc", type: "wrapper", label: "WBTC" },
    { id: "protocol:ethereum-1:bitgo", type: "protocol", label: "BitGo" },
    { id: "protocol:ethereum-1:wbtc-dao", type: "protocol", label: "WBTC DAO" },
    { id: "wrapper:ethereum-1:weeth", type: "wrapper", label: "weETH" },
    { id: "wrapper:ethereum-1:eeth", type: "wrapper", label: "eETH" },
    { id: "protocol:ethereum-1:etherfi", type: "protocol", label: "EtherFi" },
    { id: "wrapper:ethereum-1:weth", type: "wrapper", label: "WETH" },
    { id: "wrapper:ethereum-1:wsteth", type: "wrapper", label: "wstETH" },
    { id: "wrapper:ethereum-1:steth", type: "wrapper", label: "stETH" },
    { id: "protocol:ethereum-1:lido", type: "protocol", label: "Lido" },
  ],
  edges: [
    { from: ROOT, to: "protocol:ethereum-1:aave-v3", type: "protocol" },
    { from: ROOT, to: "primitive-token:ethereum-1:usdc", type: "loan" },
    { from: ROOT, to: "primitive-token:ethereum-1:aave", type: "collateral" },
    { from: ROOT, to: "wrapper:ethereum-1:btc-b", type: "collateral" },
    { from: "wrapper:ethereum-1:btc-b", to: "primitive-token:ethereum-1:btc", type: "underlying" },
    { from: "wrapper:ethereum-1:btc-b", to: "protocol:ethereum-1:avalanche-bridge", type: "protocol" },
    { from: ROOT, to: "wrapper:ethereum-1:cbbtc", type: "collateral" },
    { from: "wrapper:ethereum-1:cbbtc", to: "primitive-token:ethereum-1:btc", type: "underlying" },
    { from: "wrapper:ethereum-1:cbbtc", to: "protocol:ethereum-1:coinbase", type: "protocol" },
    { from: ROOT, to: "wrapper:ethereum-1:cbeth", type: "collateral" },
    { from: "wrapper:ethereum-1:cbeth", to: "primitive-token:ethereum-1:eth", type: "underlying" },
    { from: "wrapper:ethereum-1:cbeth", to: "protocol:ethereum-1:coinbase", type: "protocol" },
    { from: ROOT, to: "wrapper:ethereum-1:ebtc", type: "collateral" },
    { from: "wrapper:ethereum-1:ebtc", to: "primitive-token:ethereum-1:btc", type: "underlying" },
    { from: "wrapper:ethereum-1:ebtc", to: "protocol:ethereum-1:ether-fi", type: "protocol" },
    { from: ROOT, to: "wrapper:ethereum-1:fbtc", type: "collateral" },
    { from: "wrapper:ethereum-1:fbtc", to: "primitive-token:ethereum-1:btc", type: "underlying" },
    { from: "wrapper:ethereum-1:fbtc", to: "protocol:ethereum-1:frax", type: "protocol" },
    { from: ROOT, to: "wrapper:ethereum-1:lbtc", type: "collateral" },
    { from: "wrapper:ethereum-1:lbtc", to: "primitive-token:ethereum-1:btc", type: "underlying" },
    { from: "wrapper:ethereum-1:lbtc", to: "protocol:ethereum-1:lombard", type: "protocol" },
    { from: ROOT, to: "position:ethereum-1:pt-susde-5feb2026", type: "collateral" },
    { from: "position:ethereum-1:pt-susde-5feb2026", to: "wrapper:ethereum-1:susde", type: "underlying" },
    { from: "wrapper:ethereum-1:susde", to: "primitive-token:ethereum-1:usde", type: "underlying" },
    { from: "wrapper:ethereum-1:susde", to: "protocol:ethereum-1:ethena", type: "protocol" },
    { from: "position:ethereum-1:pt-susde-5feb2026", to: "protocol:ethereum-1:pendle", type: "protocol" },
    { from: ROOT, to: "position:ethereum-1:pt-usde-5feb2026", type: "collateral" },
    { from: "position:ethereum-1:pt-usde-5feb2026", to: "primitive-token:ethereum-1:usde", type: "underlying" },
    { from: "position:ethereum-1:pt-usde-5feb2026", to: "protocol:ethereum-1:pendle", type: "protocol" },
    { from: ROOT, to: "primitive-token:ethereum-1:pyusd", type: "collateral" },
    { from: ROOT, to: "wrapper:ethereum-1:reth", type: "collateral" },
    { from: "wrapper:ethereum-1:reth", to: "primitive-token:ethereum-1:eth", type: "underlying" },
    { from: "wrapper:ethereum-1:reth", to: "protocol:ethereum-1:rocket-pool", type: "protocol" },
    { from: ROOT, to: "market:ethereum-1:syrupusdt", type: "collateral" },
    { from: "market:ethereum-1:syrupusdt", to: "primitive-token:ethereum-1:usdt", type: "underlying" },
    { from: "market:ethereum-1:syrupusdt", to: "protocol:ethereum-1:maple", type: "protocol" },
    { from: ROOT, to: "wrapper:ethereum-1:tbtc", type: "collateral" },
    { from: "wrapper:ethereum-1:tbtc", to: "primitive-token:ethereum-1:btc", type: "underlying" },
    { from: "wrapper:ethereum-1:tbtc", to: "protocol:ethereum-1:threshold-network", type: "protocol" },
    { from: ROOT, to: "primitive-token:ethereum-1:usdc", type: "collateral" },
    { from: ROOT, to: "primitive-token:ethereum-1:usdt", type: "collateral" },
    { from: ROOT, to: "wrapper:ethereum-1:wbtc", type: "collateral" },
    { from: "wrapper:ethereum-1:wbtc", to: "primitive-token:ethereum-1:btc", type: "underlying" },
    { from: "wrapper:ethereum-1:wbtc", to: "protocol:ethereum-1:bitgo", type: "protocol" },
    { from: "wrapper:ethereum-1:wbtc", to: "protocol:ethereum-1:wbtc-dao", type: "protocol" },
    { from: ROOT, to: "wrapper:ethereum-1:weeth", type: "collateral" },
    { from: "wrapper:ethereum-1:weeth", to: "wrapper:ethereum-1:eeth", type: "underlying" },
    { from: "wrapper:ethereum-1:eeth", to: "primitive-token:ethereum-1:eth", type: "underlying" },
    { from: "wrapper:ethereum-1:eeth", to: "protocol:ethereum-1:ether-fi", type: "protocol" },
    { from: "wrapper:ethereum-1:weeth", to: "protocol:ethereum-1:etherfi", type: "protocol" },
    { from: "wrapper:ethereum-1:weeth", to: "primitive-token:ethereum-1:eth", type: "underlying" },
    { from: ROOT, to: "wrapper:ethereum-1:weth", type: "collateral" },
    { from: "wrapper:ethereum-1:weth", to: "primitive-token:ethereum-1:eth", type: "underlying" },
    { from: ROOT, to: "wrapper:ethereum-1:wsteth", type: "collateral" },
    { from: "wrapper:ethereum-1:wsteth", to: "wrapper:ethereum-1:steth", type: "underlying" },
    { from: "wrapper:ethereum-1:steth", to: "primitive-token:ethereum-1:eth", type: "underlying" },
    { from: "wrapper:ethereum-1:steth", to: "protocol:ethereum-1:lido", type: "protocol" },
    { from: "wrapper:ethereum-1:wsteth", to: "primitive-token:ethereum-1:eth", type: "underlying" },
    { from: "wrapper:ethereum-1:wsteth", to: "protocol:ethereum-1:lido", type: "protocol" },
  ],
}

export const SAMPLE_GRAPH_JSON = JSON.stringify(SAMPLE_GRAPH, null, 2)
