import type { DependencyGraph } from "./graph-types"

const ROOT = "market:ethereum-1:aethusdc:aethusdc"

export const SAMPLE_GRAPH: DependencyGraph = {
  root: ROOT,
  nodes: [
    {
      id: ROOT,
      type: "market",
      label: "aEthUSDC",
      provenance: "api",
      marketSupply: {
        suppliedAmount: "2119139963.676842",
        supplyCapAmount: "2500000000",
        supplyCapUsedPct: 84.76559854707368,
        suppliedUsd: 2118677079.934576,
      },
    },
    { id: "protocol:ethereum-1:aave-v3", type: "protocol", label: "Aave V3", provenance: "api" },
    {
      id: "primitive-token:ethereum-1:usdc",
      type: "primitive_token",
      label: "USDC",
      provenance: "api",
      supplyMetrics: {
        suppliedAmount: "2119139963.676842",
        supplyCapAmount: "2500000000",
        supplyCapUsedPct: 84.76559854707368,
        suppliedUsd: 2118677079.934576,
        shareOfCollateralPct: 13.779191646620168,
        maxLtvPct: 75,
        liquidationThresholdPct: 78,
        liquidationBonusPct: 4.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    {
      id: "wrapper:ethereum-1:weth",
      type: "wrapper",
      label: "WETH",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "1992013.785701382162603742",
        supplyCapAmount: "2700000",
        supplyCapUsedPct: 73.77828835931045,
        suppliedUsd: 3450446758.764792,
        shareOfCollateralPct: 22.44059163416617,
        maxLtvPct: 80.5,
        liquidationThresholdPct: 83,
        liquidationBonusPct: 5,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "primitive-token:ethereum-1:eth", type: "primitive_token", label: "ETH", provenance: "curated" },
    {
      id: "primitive-token:ethereum-1:usdt",
      type: "primitive_token",
      label: "USDT",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "2508806609.126553",
        supplyCapAmount: "3480000000",
        supplyCapUsedPct: 72.0921439404182,
        suppliedUsd: 2507172422.6775002,
        shareOfCollateralPct: 16.305839917927017,
        maxLtvPct: 75,
        liquidationThresholdPct: 78,
        liquidationBonusPct: 4.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    {
      id: "wrapper:ethereum-1:wbtc",
      type: "wrapper",
      label: "WBTC",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "32601.94729767",
        supplyCapAmount: "38200",
        supplyCapUsedPct: 85.34541177400524,
        suppliedUsd: 2011888711.1250806,
        shareOfCollateralPct: 13.084674575853805,
        maxLtvPct: 73,
        liquidationThresholdPct: 78,
        liquidationBonusPct: 5,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "primitive-token:ethereum-1:btc", type: "primitive_token", label: "BTC", provenance: "curated" },
    { id: "protocol:ethereum-1:bitgo", type: "protocol", label: "BitGo", provenance: "curated" },
    { id: "protocol:ethereum-1:wbtc-dao", type: "protocol", label: "WBTC DAO", provenance: "curated" },
    {
      id: "wrapper:ethereum-1:weeth",
      type: "wrapper",
      label: "weETH",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "984181.795357586301388341",
        supplyCapAmount: "1100000",
        supplyCapUsedPct: 89.47107230523513,
        suppliedUsd: 1873058022.5837219,
        shareOfCollateralPct: 12.181764603418229,
        maxLtvPct: 77.5,
        liquidationThresholdPct: 80,
        liquidationBonusPct: 7,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "wrapper:ethereum-1:eeth", type: "wrapper", label: "eETH", provenance: "curated" },
    { id: "protocol:ethereum-1:ether-fi", type: "protocol", label: "Ether.fi", provenance: "curated" },
    {
      id: "wrapper:ethereum-1:wsteth",
      type: "wrapper",
      label: "wstETH",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "825967.742930535608473511",
        supplyCapAmount: "1000000",
        supplyCapUsedPct: 82.59677429305356,
        suppliedUsd: 1772492249.2418587,
        shareOfCollateralPct: 11.527717284413443,
        maxLtvPct: 78.5,
        liquidationThresholdPct: 81,
        liquidationBonusPct: 6,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "wrapper:ethereum-1:steth", type: "wrapper", label: "stETH", provenance: "curated" },
    { id: "protocol:ethereum-1:lido", type: "protocol", label: "Lido", provenance: "curated" },
    {
      id: "wrapper:ethereum-1:cbbtc",
      type: "wrapper",
      label: "cbBTC",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "19515.36308764",
        supplyCapAmount: "22800",
        supplyCapUsedPct: 85.593697752807,
        suppliedUsd: 1204354724.6856213,
        shareOfCollateralPct: 7.832734265699469,
        maxLtvPct: 73,
        liquidationThresholdPct: 78,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "protocol:ethereum-1:coinbase", type: "protocol", label: "Coinbase", provenance: "curated" },
    {
      id: "wrapper:ethereum-1:lbtc",
      type: "wrapper",
      label: "LBTC",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "2054.7629503",
        supplyCapAmount: "2690",
        supplyCapUsedPct: 76.38523978810409,
        suppliedUsd: 127376363.83317032,
        shareOfCollateralPct: 0.8284147429211204,
        maxLtvPct: 70,
        liquidationThresholdPct: 75,
        liquidationBonusPct: 8.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "protocol:ethereum-1:lombard", type: "protocol", label: "Lombard", provenance: "curated" },
    {
      id: "wrapper:ethereum-1:tbtc",
      type: "wrapper",
      label: "tBTC",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "2013.923810490041809497",
        supplyCapAmount: "2500",
        supplyCapUsedPct: 80.55695241960169,
        suppliedUsd: 124285602.34458163,
        shareOfCollateralPct: 0.808313428148521,
        maxLtvPct: 73,
        liquidationThresholdPct: 78,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    {
      id: "protocol:ethereum-1:threshold-network",
      type: "protocol",
      label: "Threshold Network",
      provenance: "curated",
    },
    {
      id: "primitive-token:ethereum-1:aave",
      type: "primitive_token",
      label: "AAVE",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "807554.512007497909562887",
        supplyCapAmount: "1000000",
        supplyCapUsedPct: 80.75545120074979,
        suppliedUsd: 70729258.1569207,
        shareOfCollateralPct: 0.4600002578956384,
        maxLtvPct: 69,
        liquidationThresholdPct: 76,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    {
      id: "wrapper:ethereum-1:reth",
      type: "wrapper",
      label: "rETH",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "34433.222258653450409409",
        supplyCapAmount: "49000",
        supplyCapUsedPct: 70.27188216051724,
        suppliedUsd: 69601095.68879567,
        shareOfCollateralPct: 0.4526630534655519,
        maxLtvPct: 75,
        liquidationThresholdPct: 79,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "protocol:ethereum-1:rocket-pool", type: "protocol", label: "Rocket Pool", provenance: "curated" },
    {
      id: "primitive-token:ethereum-1:pyusd",
      type: "primitive_token",
      label: "PYUSD",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "11129522.326856",
        supplyCapAmount: "21000000",
        supplyCapUsedPct: 52.997725365980955,
        suppliedUsd: 11128178.437035032,
        shareOfCollateralPct: 0.07237407947341687,
        maxLtvPct: 75,
        liquidationThresholdPct: 78,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    {
      id: "market:ethereum-1:syrupusdt",
      type: "market",
      label: "syrupUSDT",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "9515835.924018",
        supplyCapAmount: "27200000",
        supplyCapUsedPct: 34.984690897125,
        suppliedUsd: 10784835.734477976,
        shareOfCollateralPct: 0.07014108939493438,
        maxLtvPct: 0.05,
        liquidationThresholdPct: 0.1,
        liquidationBonusPct: 6,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "protocol:ethereum-1:maple", type: "protocol", label: "Maple", provenance: "curated" },
    {
      id: "wrapper:ethereum-1:fbtc",
      type: "wrapper",
      label: "FBTC",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "174.62595443",
        supplyCapAmount: "175",
        supplyCapUsedPct: 99.78625967428572,
        suppliedUsd: 10776719.465891298,
        shareOfCollateralPct: 0.07008830380463821,
        maxLtvPct: 73,
        liquidationThresholdPct: 78,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "protocol:ethereum-1:function", type: "protocol", label: "Function", provenance: "curated" },
    {
      id: "wrapper:ethereum-1:cbeth",
      type: "wrapper",
      label: "cbETH",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "3885.534896117690236929",
        supplyCapAmount: "9000",
        supplyCapUsedPct: 43.17260995686322,
        suppliedUsd: 7634591.931513569,
        shareOfCollateralPct: 0.04965292085536415,
        maxLtvPct: 75,
        liquidationThresholdPct: 79,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    {
      id: "wrapper:ethereum-1:ebtc",
      type: "wrapper",
      label: "eBTC",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "81.59891997",
        supplyCapAmount: "134",
        supplyCapUsedPct: 60.89471639552239,
        suppliedUsd: 5054642.201029683,
        shareOfCollateralPct: 0.03287376082589836,
        maxLtvPct: 67,
        liquidationThresholdPct: 72,
        liquidationBonusPct: 10,
        isFrozen: false,
        isPaused: false,
      },
    },
    {
      id: "wrapper:ethereum-1:btc-b",
      type: "wrapper",
      label: "BTC.b",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "7.0265637",
        supplyCapAmount: "10",
        supplyCapUsedPct: 70.265637,
        suppliedUsd: 433631.449868292,
        shareOfCollateralPct: 0.002820198938443923,
        maxLtvPct: 73,
        liquidationThresholdPct: 78,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "protocol:ethereum-1:avalanche-bridge", type: "protocol", label: "Avalanche Bridge", provenance: "curated" },
    {
      id: "position:ethereum-1:pt-susde-5feb2026",
      type: "position",
      label: "PT-sUSDE-5FEB2026",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "20388.243093646729930744",
        supplyCapAmount: "1",
        supplyCapUsedPct: 2038824.3093646732,
        suppliedUsd: 20374.96259986039,
        shareOfCollateralPct: 0.00013251217805446036,
        maxLtvPct: 0.05,
        liquidationThresholdPct: 0.1,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
    { id: "wrapper:ethereum-1:susde", type: "wrapper", label: "sUSDe", provenance: "curated" },
    { id: "wrapper:ethereum-1:usde", type: "wrapper", label: "USDe", provenance: "curated" },
    { id: "protocol:ethereum-1:ethena", type: "protocol", label: "Ethena", provenance: "curated" },
    { id: "protocol:ethereum-1:pendle", type: "protocol", label: "Pendle", provenance: "curated" },
    {
      id: "position:ethereum-1:pt-usde-5feb2026",
      type: "position",
      label: "PT-USDe-5FEB2026",
      provenance: "curated",
      supplyMetrics: {
        suppliedAmount: "1803.847525772159785781",
        supplyCapAmount: "1",
        supplyCapUsedPct: 180384.752577216,
        suppliedUsd: 1802.6725355708222,
        shareOfCollateralPct: 0.00001172400012204602,
        maxLtvPct: 0.05,
        liquidationThresholdPct: 0.1,
        liquidationBonusPct: 7.5,
        isFrozen: false,
        isPaused: false,
      },
    },
  ],
  edges: [
    { from: ROOT, to: "protocol:ethereum-1:aave-v3", type: "protocol", provenance: "api" },
    { from: ROOT, to: "primitive-token:ethereum-1:usdc", type: "loan", provenance: "api" },
    { from: ROOT, to: "wrapper:ethereum-1:weth", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:weth", to: "primitive-token:ethereum-1:eth", type: "underlying", provenance: "curated" },
    { from: ROOT, to: "primitive-token:ethereum-1:usdt", type: "collateral", provenance: "curated" },
    { from: ROOT, to: "primitive-token:ethereum-1:usdc", type: "collateral", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:wbtc", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:wbtc", to: "primitive-token:ethereum-1:btc", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:wbtc", to: "protocol:ethereum-1:bitgo", type: "protocol", provenance: "curated" },
    { from: "wrapper:ethereum-1:wbtc", to: "protocol:ethereum-1:wbtc-dao", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:weeth", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:weeth", to: "wrapper:ethereum-1:eeth", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:eeth", to: "primitive-token:ethereum-1:eth", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:eeth", to: "protocol:ethereum-1:ether-fi", type: "protocol", provenance: "curated" },
    { from: "wrapper:ethereum-1:weeth", to: "protocol:ethereum-1:ether-fi", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:wsteth", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:wsteth", to: "wrapper:ethereum-1:steth", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:steth", to: "primitive-token:ethereum-1:eth", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:steth", to: "protocol:ethereum-1:lido", type: "protocol", provenance: "curated" },
    { from: "wrapper:ethereum-1:wsteth", to: "protocol:ethereum-1:lido", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:cbbtc", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:cbbtc", to: "primitive-token:ethereum-1:btc", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:cbbtc", to: "protocol:ethereum-1:coinbase", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:lbtc", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:lbtc", to: "primitive-token:ethereum-1:btc", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:lbtc", to: "protocol:ethereum-1:lombard", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:tbtc", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:tbtc", to: "primitive-token:ethereum-1:btc", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:tbtc", to: "protocol:ethereum-1:threshold-network", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "primitive-token:ethereum-1:aave", type: "collateral", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:reth", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:reth", to: "primitive-token:ethereum-1:eth", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:reth", to: "protocol:ethereum-1:rocket-pool", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "primitive-token:ethereum-1:pyusd", type: "collateral", provenance: "curated" },
    { from: ROOT, to: "market:ethereum-1:syrupusdt", type: "collateral", provenance: "curated" },
    { from: "market:ethereum-1:syrupusdt", to: "primitive-token:ethereum-1:usdt", type: "underlying", provenance: "curated" },
    { from: "market:ethereum-1:syrupusdt", to: "protocol:ethereum-1:maple", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:fbtc", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:fbtc", to: "primitive-token:ethereum-1:btc", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:fbtc", to: "protocol:ethereum-1:function", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:cbeth", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:cbeth", to: "primitive-token:ethereum-1:eth", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:cbeth", to: "protocol:ethereum-1:coinbase", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:ebtc", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:ebtc", to: "primitive-token:ethereum-1:btc", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:ebtc", to: "protocol:ethereum-1:ether-fi", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "wrapper:ethereum-1:btc-b", type: "collateral", provenance: "curated" },
    { from: "wrapper:ethereum-1:btc-b", to: "primitive-token:ethereum-1:btc", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:btc-b", to: "protocol:ethereum-1:avalanche-bridge", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "position:ethereum-1:pt-susde-5feb2026", type: "collateral", provenance: "curated" },
    { from: "position:ethereum-1:pt-susde-5feb2026", to: "wrapper:ethereum-1:susde", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:susde", to: "wrapper:ethereum-1:usde", type: "underlying", provenance: "curated" },
    { from: "wrapper:ethereum-1:usde", to: "protocol:ethereum-1:ethena", type: "protocol", provenance: "curated" },
    { from: "wrapper:ethereum-1:susde", to: "protocol:ethereum-1:ethena", type: "protocol", provenance: "curated" },
    { from: "position:ethereum-1:pt-susde-5feb2026", to: "protocol:ethereum-1:pendle", type: "protocol", provenance: "curated" },
    { from: ROOT, to: "position:ethereum-1:pt-usde-5feb2026", type: "collateral", provenance: "curated" },
    { from: "position:ethereum-1:pt-usde-5feb2026", to: "wrapper:ethereum-1:usde", type: "underlying", provenance: "curated" },
    { from: "position:ethereum-1:pt-usde-5feb2026", to: "protocol:ethereum-1:pendle", type: "protocol", provenance: "curated" },
  ],
}

export const SAMPLE_GRAPH_JSON = JSON.stringify(SAMPLE_GRAPH, null, 2)
