export const TOKEN_DEPENDENCIES_PROMPT = [
  'Classify one DeFi token and return all of its direct dependencies.',
  'The input token may represent a primitive asset, wrapped token, LP token, protocol position, lending market, or other tokenized claim.',
  'Return one result for the input token, preserving the input symbol.',
  'Classify the input according to what it represents: base asset, plain token, wrapped token, LP token, protocol position, lending market, protocol, or another tokenized claim.',
  'Treat a base asset or plain stablecoin with no relevant DeFi dependency as primitive, such as USDC, DAI, ETH, BTC, or a plain governance token.',
  'Do not treat a token as primitive just because it is an ERC20.',
  'Classify a wrapped or tokenized claim asset as wrapper unless it is clearly a protocol position, LP token, or lending market.',
  'A symbol with prefixes/suffixes like w, st, yv, a, c, cb, t, rs, ez, we, or names suggesting share/receipt/vault/staked/wrapped is usually not primitive.',
  'Do not infer wrapper only from the prefix s; an s-prefixed asset is often a protocol position or market.',
  'Classify a Maple Syrup token such as syrupUSDT, syrupUSDC, or syrupUSDS as market, not wrapper.',
  'Examples: wstETH is wrapper over stETH or ETH; weETH is wrapper over eETH or ETH; rETH is wrapper over ETH; sDAI is position over DAI; a BTC wrapper such as WBTC, cbBTC, tBTC, or LBTC is wrapper over BTC.',
  'Use wrapper for a wrapped token, lp for a liquidity pool token, position for a receipt/vault/deposit token, and market for a lending market.',
  'For a primitive token, return no dependencies.',
  'For wrapper, lp, position, or market, return every known direct dependency and no recursive dependencies.',
  'For each dependency, classify what that dependency is using the same categories.',
  'A primitive dependency is an asset that the input token wraps, represents, is redeemable for, is priced from, or has as an underlying asset.',
  'A protocol dependency is a protocol, issuer, bridge, vault protocol, staking system, exchange, or market that creates, manages, or backs the input token.',
  'A dependency can also be wrapper, lp, position, or market if the direct dependency is itself a tokenized claim or market token.',
  'Do not omit a protocol dependency just because an underlying token dependency is also present.',
  'Examples: wstETH depends on stETH as wrapper, ETH as primitive, and Lido as protocol; WBTC depends on BTC as primitive and BitGo/WBTC DAO as protocol; syrupUSDT depends on USDT as primitive and Maple as protocol; a Pendle PT token such as PT-sUSDE depends on its underlying asset and Pendle as protocol.',
  'If unsure, classify the token as primitive and return no dependencies.',
].join(' ')
